FROM node:22-alpine3.19

WORKDIR /usr/src/app

RUN apk update && apk add && apk add ffmpeg

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "start:dev"]

