---
version: "3"

name: video-processing
services:
  frontend:
    build:
      context: ../apps/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3000
    volumes:
      - ../apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - API_BASE_URL=http://backend:3000
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    depends_on:
      - backend

  backend:
    build:
      context: ../apps/backend/
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - ../apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_ID=test
      - AWS_ACCESS_SECRET=test
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/queue
      - S3_BUCKETS_BASE_URL=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs,dynamodb
      - LS_LOG=warn
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./localstack/ready.sh:/etc/localstack/init/ready.d/ready.sh"

    healthcheck:
      test: ["CMD", "awslocal", "sqs", "list-queues"]
      interval: 1s
      timeout: 5s
      retries: 30